server {
    listen 80;
    server_name music.iamshadow.link;

    # Root directory where the built files are
    root /usr/share/nginx/html;
    index index.html;

    location / {
        # This is the magic line for SPA routing (React/Vite)
        try_files $uri $uri/ /index.html;
    }

    # API Proxy
    location /api/ {
        proxy_pass http://my-service-back:5000; # Use the service name from Docker Compose/K8s
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Socket.io Proxy
    location /socket.io/ {
        proxy_pass http://my-service-back:5000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }
}